### ISSUE TITLE
SkyBox doesn't support moving camera

### ISSUE THREAD

**Issue by Alexx999** [aerys/minko-examples#9]
If we move camera skybox breaks, while proper implementation shouldn't depend on camera position

**Comment by JMLX42** [comment]
Thank you for your feedback.
Two ways to fix this:

1) in the shader:

<pre>
// translate the vertex position by the camera position to center the skybox on the camera
var skyboxPixelPosition : SFloat    = interpolate(add(
    localToWorld(getVertexAttribute(VertexComponent.XYZ)),
    cameraPosition
));
</pre>

2) or on the CPU:

<pre>
override protected function enterFrameHandler(event : Event) : void
{
  var cameraPosition : Vector4 = camera.transform.getTranslation();
            
  _skybox.transform.setTranslation(
    cameraPosition.x,
    cameraPosition.y,
    cameraPosition.z
  );
  super.enterFrameHandler(event);
}
</pre>

Of course, I prefer the first one :)
But that's debatable depending on your actual requirements in your app...

Fixed in dcffff48d2fdd3a6ef59795dd2a68e97a58df3e7

**Comment by Alexx999** [comment]
Skybox still broken - it's possible to move camera out of it and it's distance culled
http://clip2net.com/s/2nH1s

**Comment by JMLX42** [comment]
my bad, I fixed the fragment shader when I should have fixed the vertex shader to make sure vertices are translated according to the camera position

fixed in b84fe080517a9ec1533c8262e4242e0e0bf402ed

tell me how it works for you!

**Comment by Alexx999** [comment]
well, very same thing as on that screenshot.
in fact, it's now broken even worse - if you look at that screenshot it's noticeable that it's really a box with texture on inner surface, while old code (in master branch) makes proper "window" style effect: http://clip2net.com/s/2nHR7

**Comment by JMLX42** [comment]
Are you sure you scaled the skybox? It works pretty well in SkyboxExample...

**Comment by Alexx999** [comment]
for me it throws exception on

```
position.incrementBy(float4(cameraPosition, 0));
```

but works with

```
position.incrementBy(cameraPosition);
```

and frustum culling does not disable distance culling (I've tried to set it to disabled myself)
and yes, scale is set

copied over code gives me following (as addition to being distance culled):
http://clip2net.com/s/2nI3y

**Comment by JMLX42** [comment]
<pre>for me it throws exception</pre>

fixed in 7d661a614b598a7782295f6bc8230c3d42a60dca

<pre>frustum culling</pre>

disabled in d897706d323f62b696fff88da38247db20aa52d4

<pre>distance culling</pre>

It should never happen since the skybox is always centered on the camera...

**Comment by Alexx999** [comment]
Okay, I tried example and it now works there, so I suppose it's once again issue about something done wrong way

**Comment by JMLX42** [comment]
Ok cool :)
If you need help : http://answers.aerys.in/
